name: Btrback
version: @version@
main: net.himeki.btrback.Btrback
api-version: 1.13
authors: [Grider]
description: A minecraft backup plugin which takes advance of btrfs snapshot mechanism

commands:
  btrback:

permissions:
  btrback.backup:
    description: permission to backup
  btrback.rollback:
    description: permission to rollback
  btrback.reload:
    description: permission to reload plugin
  btrback.purge:
    description: permission to purge old backups